### ISSUE TITLE
Latest Soma blinds not detecting

### ISSUE THREAD

**Issue by tiimbo82** [andersonshatch/soma-ctrl#27]
New blinds have a new bluetooth "hostname", cannot be detected

**Comment by andersonshatch** [comment]
Can you try out this branch and let me know if it improves things @tiimbo82?

Steps would be:

1.  clone the repo: `git clone https://github.com/andersonshatch/soma-ctrl`
2. `cd soma-ctrl`
2. Checkout the new branch: `git checkout manual-ids`
3. Install the dependencies: `npm install`
3. Run the tool with the new format IDs specified explicitly: `sudo node index.js --mqtt-url mqtt://etcetc f023c6wu f023c6fa`

**Comment by tiimbo82** [comment]
Hey, I've just done a test and they are the wrong ID's sorry.
Soma have replaced the the ID's with just "S", really weird.
Is there anyway to connect via mac?
![screenshot_20181120-180802](https://user-images.githubusercontent.com/36907258/48767412-d099db00-ed0a-11e8-828a-e65b499ff663.png)
![screenshot_20181120-180828](https://user-images.githubusercontent.com/36907258/48767423-d68fbc00-ed0a-11e8-8340-64cbd58907c8.png)

**Comment by andersonshatch** [comment]
Thanks for the extra details @tiimbo82 
I just pushed some extra changes to that branch that should allow you to specify MAC addresses to connect to instead.
Can you please try it out and let me know how it looks?

Please put the MAC addresses in in lowercase, e.g.:
`sudo node index.js --mqtt-url mqtt://etcetc f5:36:0f:7e:90:94`

**Comment by tiimbo82** [comment]
still no good unfortunately, here's output:

pi@raspberrypi:~/soma-ctrl $ sudnode index.js --mqtt-url mqtt://192.168.48.249 f7:bf:9f:8f:28:8b
soma* scanning for 1 device(s) [ 'f7bf9f8f288b' ] +0ms


what should i expect after that?

**Comment by andersonshatch** [comment]
In an ideal case it'd connect to the device...
I've just pushed a build with some extra debug logging, can you pull it down and share the output?
Please make sure to run with the `-d` option which enables debug logging output. It should log anything it discovers

**Comment by tiimbo82** [comment]
Output:

 soma Unmatched device: {"id":"f7bf9f8f288b","address":"f7:bf:9f:8f:28:8b","addressType":"random","connectable":true,"advertisement":{"localName":"S","manufacturerData":{"type":"Buffer","data":[112,3,1,56,0,0,77,97,105,110,32,66,101,100,114,111,111,109,49,32,32]},"serviceData":[],"serviceUuids":[],"solicitationServiceUuids":[],"serviceSolicitationUuids":[]},"rssi":-83,"state":"disconnected"} +96ms

**Comment by ronvl** [comment]
Hey got the same problem here... the scan shows them as:
[NEW] Device E2:E4:81:69:E8:05 S
[NEW] Device FD:BD:B4:7F:4F:7A S

**Comment by andersonshatch** [comment]
Hmm, I think I may have been looking at the wrong attribute on the device when trying to match against the MAC address(es) provided. Just pushed a new commit to address that, let's see whether that's any better for you both.

**Comment by ronvl** [comment]
Looks like it worked:
root@NUC7i3BNH:/usr/src/node-red/soma-ctrl# node index.js -l 3000 -t 180 e2:e4:81:69:e8:05
  soma* scanning for 1 device(s) [ 'e2e48169e805' ] +0ms
  soma* connected to S +533ms
  soma* all expected devices connected, stopping scan +1ms

Will try to get it in HASS over the next days.

Thanks for your support!!!

**Comment by andersonshatch** [comment]
Awesome to hear. Hopefully it'll be the same for @tiimbo82 too!
I will probably continue pushing a few more changes and fixes to this branch before releasing, but I'll post here when it's released and available on NPM.

**Comment by tiimbo82** [comment]
you are a legend, thankyou! where is the paypal donate link??

**Comment by andersonshatch** [comment]
Pushed some more changes, including to discover devices named "S" since that seems to be the theme... I'll release to NPM soon if it continues to be stable.

https://monzo.me/joshanderson or https://www.paypal.me/andersonshatch if you insist; in which case ❤️

**Comment by ronvl** [comment]
Hi 

Did some testing today with your latest test version but seems not quit working yet...

noble warning: unknown peripheral fdbdb47f4f7a
  soma* connected to fdbdb47f4f7a +51ms
  soma* connected to fdbdb47f4f7a +56ms
noble warning: unknown peripheral fdbdb47f4f7a
(node:85) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 servicesDiscover listeners added. Use emitter.setMaxListeners() to increase limit
  soma* connected to fdbdb47f4f7a +274ms
noble warning: unknown handle 3585 disconnected!
noble: unknown peripheral e2e48169e805 connected!

So the addresses are the right ones for my two soma devices but HASS sometimes works and some times it doesn't........ if I restart the container it works again ....

**Comment by ronvl** [comment]
another problem I have is that it seems that it is not releasing the bluetooth controler as all my other bluetooth devices in HASS are not updating anymore when soma-ctrl is running....

I'm running docker with node-red and HASS on the same host.

**Comment by andersonshatch** [comment]
The servicesDiscover memory leak warning is something I've seen, and looked into to see if it was my doing, but it's out of my hands, seemingly a bug in noble (the node BTLE library this projects) or its bindings for particular OS/Bluetooth stacks. Doesn't seem to affect stability for me.

There's also seemingly issues with noble getting upset when other processes are using noble or possibly even BT in general, which again is not really something I can do much about as a dependent to that library.
I have another branch that waits until the expected number of devices have been discovered first before connecting to them that seems a little better on a pi (finally got a recent one to test this with, as I was previously only using a Mac), but not sure if it'll help with this.

Anyway, I think neither issue here is directly related to the device name changing which was the original issue, so it makes more sense to go into a separate issue. Not sure I can do much about them though, as I say.

**Comment by andersonshatch** [comment]
Resolved in 1.2.0 published to npm

**Comment by ronvl** [comment]
Hi Josh

I have seen you pushed it to NMP so will start testing with the new one.

I understand from your comments that the proble is in the BLE stack so will
need to find a different solution as the current one using Docker isn't
very stable...

This is the result of an half hour running:
  soma* connected to fdbdb47f4f7a +23s
  soma* connected to fdbdb47f4f7a +147ms
  soma* connected to fdbdb47f4f7a +2s
  soma* connected to fdbdb47f4f7a +167ms
  soma* connected to fdbdb47f4f7a +6s
  soma* connected to fdbdb47f4f7a +433ms
  soma* connected to fdbdb47f4f7a +182ms
  soma* connected to fdbdb47f4f7a +51ms
noble warning: unknown peripheral fdbdb47f4f7a

It connect to the two devices but after some time it doesn't recognise it
anymore... Happy to open an issue on Github if you are willing to look at it

Thanks for your help!

Ron
