### ISSUE TITLE
Latest version only connect to one device

### ISSUE THREAD

**Issue by ronvl** [andersonshatch/soma-ctrl#36]
Hi Josh,

I wanted to connect second device (I have 3 in total) after instelling it all on a PI as the docker setup didn't work in combination with HASS and BLE devices but it seems that the last version only connects to the first device it finds.... it connects to both but not at the same time
I have done various test to make sure that it isn't my installation:
- timer on 120 seconds - but only finds one... 
- Devices to look for 2 ... same result
- node /home/pi/node_modules/soma-ctrl/index.js e2e48169e805 fdbdb47f4f7a --url mqtt:192.168.2.192:1883 ----- it always connects to e2e48169e805 ie the first one
- node /home/pi/node_modules/soma-ctrl/index.js fdbdb47f4f7a e2e48169e805 --url mqtt:192.168.2.192:1883 ----- it always connects to fdbdb47f4f7a ie again the first one

Can you have a look at this please?
Thanks
Ron

**Comment by andersonshatch** [comment]
I think this might be due to a noble restriction, but I already have a branch to try and address it, it's been waiting for other testers / complaints of the same symptom.
Can you try and let me know? Steps:

1. clone the repo: `git clone https://github.com/andersonshatch/soma-ctrl`
1. `cd soma-ctrl`
1. Checkout the new branch: `git checkout discover-all-then-connect`
1. Install the dependencies: `npm install`

**Comment by ronvl** [comment]
this one is indeed working. Thanks!

I do see a lot of connects though and wonder if that is expected ... my screen is constantly scrolling with:
  soma* scanning for 2 device(s) [ 'fdbdb47f4f7a', 'e2e48169e805' ] +0ms
  soma* connected to fdbdb47f4f7a +916ms
  soma* connected to fdbdb47f4f7a +28ms
  soma* connected to fdbdb47f4f7a +7ms
  soma* connected to e2e48169e805 +361ms
  soma* all expected devices connected, stopping scan +0ms
  soma* connected to e2e48169e805 +951ms
  soma* connected to e2e48169e805 +13s
  soma* connected to e2e48169e805 +5s
  soma* connected to e2e48169e805 +300ms
  soma* connected to e2e48169e805 +300ms
  soma* connected to e2e48169e805 +300ms
  soma* connected to e2e48169e805 +745ms
  soma* connected to e2e48169e805 +8s
  soma* connected to e2e48169e805 +4s
  soma* connected to e2e48169e805 +5s
  soma* connected to e2e48169e805 +188ms
  soma* connected to e2e48169e805 +717ms
  soma* connected to e2e48169e805 +16s
  soma* connected to e2e48169e805 +25s
  soma* connected to e2e48169e805 +4s
  soma* connected to e2e48169e805 +8s
  soma* connected to e2e48169e805 +2s
  soma* connected to e2e48169e805 +200ms
  soma* connected to e2e48169e805 +2s
  soma* connected to e2e48169e805 +15s
  soma* connected to e2e48169e805 +7s
  soma* connected to e2e48169e805 +3s
  soma* connected to e2e48169e805 +442ms

Also after some time I get multiple:
(node:6405) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 characteristicsDiscover listeners added. Use emitter.setMaxListeners() to increase limit

This doesn't seem to effect functionality though...

One other problem I got a few times is:
pi@soma-ctrl:~/soma-ctrl $ sudo node /home/pi/node_modules/soma-ctrl/index.js fdbdb47f4f7a e2e48169e805 --url mqtt:192.168.2.192:1883
  soma* scanning for 2 device(s) [ 'fdbdb47f4f7a', 'e2e48169e805' ] +0ms
  soma* connected to fdbdb47f4f7a +516ms
/home/pi/node_modules/soma-ctrl/src/SomaShade.js:147
                this.positionCharacteristic.subscribe();
                                            ^

TypeError: Cannot read property 'subscribe' of undefined
    at peripheral.discoverSomeServicesAndCharacteristics (/home/pi/node_modules/soma-ctrl/src/SomaShade.js:147:45)
    at Peripheral.<anonymous> (/home/pi/node_modules/noble/lib/peripheral.js:101:13)
    at Service.<anonymous> (/home/pi/node_modules/noble/lib/service.js:53:7)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Service.emit (events.js:211:7)
    at Noble.onCharacteristicsDiscover (/home/pi/node_modules/noble/lib/noble.js:302:13)
    at emitThree (events.js:136:13)
    at NobleBindings.emit (events.js:217:7)
    at NobleBindings.onCharacteristicsDiscovered (/home/pi/node_modules/noble/lib/hci-socket/bindings.js:339:8)

If you want me to open  a new issue for one of the above let me know

Cheers
Ron

**Comment by andersonshatch** [comment]
Connecting only to the first discovered device and the crash with `Cannot read property 'subscribe' of undefined` should both be addressed by v1.3.0 which I just released.
I've looked into those MaxListenersExceededWarnings before, and most of them I can't do anything about, but they don't seem to affect stability.
