### ISSUE TITLE
Issues installing - directory not created

### ISSUE THREAD

**Issue by ThomasPrior** [andersonshatch/soma-ctrl#61]
Have attempted installation using NodeJS 9.11.2 on Rasbian on a Pi 3B and Debian Buster, both installation commads (sudo npm install -g soma-ctl) result in a seemingly endless loop of errors and retries:

```
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/soma-ctrl/node_modules/usb/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/soma-ctrl/node_modules/usb/.node-gyp/9.11.2"

```

The installation does not complete.

Manually creating the directory at /usr/lib/node_modules/soma-ctrl/node_modules/usb/.node-gyp/ allows the installation to complete.

**Comment by andersonshatch** [comment]
Do you have the command line output from this by any chance?
I wonder if there is some need to also add in --unsafe-perm when running as root depending on where npm is trying to install
