### ISSUE TITLE
TypeError: Cannot read property 'subscribe' of undefined

### ISSUE THREAD

**Issue by sdasmith** [andersonshatch/soma-ctrl#8]
Hi @andersonshatch 

We were discussing this a little while ago on the Home Assistant Forums. I'm still having the positionCharacteristic:

```
pi@raspberrypi:~ $ sudo /opt/nodejs/bin/somactrl -e 1 --mqtt-url mqtt://10.0.1.3
  soma* No device names supplied, will stop scanning after 1 device(s) connect +0ms
  soma* scanning for 1 device(s) [] +39ms
  soma* connected to RISE62 +2s
  soma* all expected devices connected, stopping scan +3ms
/opt/nodejs/lib/node_modules/soma-ctrl/src/SomaShade.js:147
                this.positionCharacteristic.subscribe();
                                            ^

TypeError: Cannot read property 'subscribe' of undefined
    at peripheral.discoverSomeServicesAndCharacteristics (/opt/nodejs/lib/node_modules/soma-ctrl/src/SomaShade.js:147:45)
    at Peripheral.<anonymous> (/opt/nodejs/lib/node_modules/soma-ctrl/node_modules/noble/lib/peripheral.js:101:13)
    at Service.<anonymous> (/opt/nodejs/lib/node_modules/soma-ctrl/node_modules/noble/lib/service.js:53:7)
    at Object.onceWrapper (events.js:324:30)
    at emitOne (events.js:125:13)
    at Service.emit (events.js:221:7)
    at Noble.onCharacteristicsDiscover (/opt/nodejs/lib/node_modules/soma-ctrl/node_modules/noble/lib/noble.js:302:13)
    at emitThree (events.js:145:13)
    at NobleBindings.emit (events.js:227:7)
    at NobleBindings.onCharacteristicsDiscovered (/opt/nodejs/lib/node_modules/soma-ctrl/node_modules/noble/lib/hci-socket/bindings.js:339:8)
```
Let me know if you need anymore details

**Comment by andersonshatch** [comment]
Hey, thanks for following up on this here.

I've just pushed a change with some extra debugging to a branch, it should print out which characteristics weren't found, and the ones that your device has instead. 
Without the position characteristic I'm not sure how to control the device, but hopefully this will at least rule out any silly mistakes or if the tool is connecting to another device entirely.

Can you try it out?

Steps would be:

1.  clone the repo: `git clone https://github.com/andersonshatch/soma-ctrl`
2. `cd soma-ctrl`
2. Checkout the new branch: `git checkout debug-missing-characteristics`
3. Install the dependencies: `npm install`
3. Run the tool and wait for some debug info: `sudo node index.js -e 1 --mqtt-url mqtt://etcetc`

I'm expecting some messages like the following which is what I'd like to examine from your setup:

```
 soma:RISE148 0000 not found +853ms
  soma:RISE148 ERROR: missing some expected characteristics +0ms
  soma:RISE148 device has the following available: [ '180a - 2a29,2a25,2a27,2a26,2a28',
  '180f - 2a19',
  '00001554b87f490c92cb11ba5ea5167c - 00001555b87f490c92cb11ba5ea5167c',
  '00001861b87f490c92cb11ba5ea5167c - 00001525b87f490c92cb11ba5ea5167c,00001526b87f490c92cb11ba5ea5167c,00001527b87f490c92cb11ba5ea5167c,00001528b87f490c92cb11ba5ea5167c,00001529b87f490c92cb11ba5ea5167c,00001530b87f490c92cb11ba5ea5167c,00001531b87f490c92cb11ba5ea5167c,00001533b87f490c92cb11ba5ea5167c,0000ba71b87f490c92cb11ba5ea5167c,0000ba72b87f490c92cb11ba5ea5167c',
  '00001890b87f490c92cb11ba5ea5167c - 00001891b87f490c92cb11ba5ea5167c,00001892b87f490c92cb11ba5ea5167c,00001893b87f490c92cb11ba5ea5167c,00001894b87f490c92cb11ba5ea5167c' ]
```

**Comment by sdasmith** [comment]
Thanks for that @andersonshatch 

It connected, but then disconnects:

```
pi@raspberrypi:~/soma-ctrl $ sudo node index.js -e 1 --mqtt-url mqtt://10.0.1.3
  soma* No device names supplied, will stop scanning after 1 device(s) connect +0ms
  soma* scanning for 1 device(s) [] +41ms
  soma* connected to RISE62 +2s
  soma* all expected devices connected, stopping scan +3ms
  soma:RISE62 00001525b87f490c92cb11ba5ea5167c not found +0ms
  soma:RISE62 00001526b87f490c92cb11ba5ea5167c not found +2ms
  soma:RISE62 00001530b87f490c92cb11ba5ea5167c not found +2ms
  soma:RISE62 2a19 not found +2ms
  soma:RISE62 00001893b87f490c92cb11ba5ea5167c not found +3ms
  soma:RISE62 00001892b87f490c92cb11ba5ea5167c not found +3ms
  soma:RISE62 00001531b87f490c92cb11ba5ea5167c not found +3ms
  soma:RISE62 00001529b87f490c92cb11ba5ea5167c not found +5ms
  soma:RISE62 ERROR: missing some expected characteristics +3ms
  soma:RISE62 disconnected +2s
  soma:RISE62 connected for 2.6 seconds +22ms
  soma* connected to RISE62 +3s
  soma:RISE62 connected! +140ms
  soma:RISE62 position 20 +3s
  soma:RISE62 group: Living room +81ms
  soma:RISE62 name: Living room1 +63ms
  soma:RISE62 battery at 29% +184ms
  soma:RISE62 disconnected +3m
  soma:RISE62 connected for 183.5 seconds +14ms
  soma* connected to RISE62 +3m
  soma:RISE62 connected! +161ms
  soma:RISE62 position 20 +4s
  soma:RISE62 battery at 29% +748ms
  soma:RISE62 disconnected +3m
  soma:RISE62 connected for 185.074 seconds +14ms
```

I used the control.py script to control the position before:
https://github.com/sdasmith/soma-smart-shade-homekit-script/blob/master/control.py#L51

Thanks!

**Comment by andersonshatch** [comment]
Thanks for trying that out... 
From my experience it seems normal that these devices only maintain an open connection for a few minutes and the script should reconnect after those disconnects.

From this test it actually looks like it got connected after the first time when there were some missing characteristics, which seems really odd. Does that happen each time you try running the script?
Were you able to control it for some time? Looking at the logs there was a 183 second and 185 second opportunity where it looks like things were actually all set up properly.

I have seen very occasional crashes myself from missing characteristics on a device, which I need to handle better, and perhaps this branch is a good first start for that.

**Comment by andersonshatch** [comment]
Any updates on this one @sdasmith?

**Comment by sdasmith** [comment]
Hi @andersonshatch yup, I got it working like I outlined here:
https://community.home-assistant.io/t/soma-blind-control-via-mqtt/52422/18?u=stephensmith
Closing this issue
